services:
  web:
    build: .
    command: python -u app.py
    ports:
      - "5005:5005"
    depends_on:
      - db
    environment:
      - MONGO_URI=mongodb://db:27017 # Connect to MongoDB service
  db:
    image: mongo:latest
